#pragma once

#include "Common/CommonTypes.h"

#include "WHDCommonTypes.generated.h"

/**
 * 交互选项
 */
UENUM(BlueprintType)
enum class EWHDInteractAction : uint8
{
	// 无
	None = EInteractAction::None UMETA(DisplayName="无"),
	// 进入
	Enter = EInteractAction::Custom3 UMETA(DisplayName="进入"),
	// 切换
	Switch = EInteractAction::Custom4 UMETA(DisplayName="切换")
};

namespace GameplayTags
{
	////////////////////////////////////////////////////
	// Input_Player
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);

	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact4);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact5);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleCrouch);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleLockSightTarget);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Primary);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Secondary);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ReleaseSkillAbility1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ReleaseSkillAbility2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ReleaseSkillAbility3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ReleaseSkillAbility4);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UseInventoryItem);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_DiscardInventoryItem);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_PrevInventorySlot);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_NextInventorySlot);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot4);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot5);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot6);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot7);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot8);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot9);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectInventorySlot10);
	
	////////////////////////////////////////////////////
	// Input_System
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_OpenInventoryPanel);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_OpenGeneratePanel);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_PauseGame);
};
