#pragma once

#include "Ability/AbilityModuleTypes.h"

#include "WHDCommonTypes.generated.h"

/**
 * 交互选项
 */
UENUM(BlueprintType)
enum class EWHDInteractAction : uint8
{
	// 无
	None = EInteractAction::None UMETA(DisplayName="无"),
	// 进入
	Enter = EInteractAction::Custom3 UMETA(DisplayName="进入"),
	// 切换
	Switch = EInteractAction::Custom4 UMETA(DisplayName="切换")
};

namespace GameplayTags
{
	////////////////////////////////////////////////////
	// Input_Player
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);

	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact4);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact5);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleCrouch);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleLockSightTarget);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Primary);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Minor);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReleaseSkillAbility1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReleaseSkillAbility2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReleaseSkillAbility3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReleaseSkillAbility4);
	
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseInventoryItem);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_DiscardInventoryItem);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrevInventorySlot);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_NextInventorySlot);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot1);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot2);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot3);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot4);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot5);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot6);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot7);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot8);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot9);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectInventorySlot10);
	
	////////////////////////////////////////////////////
	// State_Character
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Dodging);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Sprinting);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Crouching);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Swimming);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Floating);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Climbing);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Riding);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Flying);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Attacking);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_NormalAttacking);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_FallingAttacking);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_SkillAttacking);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Defending);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Interrupting);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_Exhausted);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_FreeToAnim);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_LockRotation);
	WHFRAMEWORKDEMO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTag_Character_BreakAllInput);
};
